name: social_test
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 3.1.1+9

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

 # rounded_flutter_datetime_picker: ^1.3.11
 # file_picker: ^4.0.0
 # material_design_icons_flutter: 4.0.5955
 # flutter_facebook_auth: "^3.5.0"
 # flutter_launcher_icons: ^0.7.3
  badges: ^1.1.0
  fluttertoast: ^8.0.8
  awesome_notifications: 0.0.6+10
  sn_progress_dialog: ^1.0.3
  stylish_dialog: ^0.0.6
  url_launcher: ^5.4.0
  file_picker: ^2.1.7
  flutter_facebook_login: ^3.0.0
  flutter_signin_button: ^2.0.0
  dropdown_search: ^0.6.3
  font_awesome_flutter: ^9.1.0
  minimal_onboarding: ^1.0.0
  shared_preferences: ^0.5.12
  cloud_firestore: ^0.9.7+2
  image_picker: ^0.6.0+2
  firebase_storage: ^2.1.0+1
  firebase_auth: ^0.8.3
  firebase_core: ^0.3.0
  expandable_text: 2.2.0
  google_sign_in: ^4.0.1+1
  geolocator: 5.0.1
  uuid: ^2.0.0
  image: ^2.0.7
  animator: ^3.1.0
  cupertino_icons: ^0.1.2
  path_provider: ^0.5.0+1
  firebase_messaging: ^4.0.0+1
  timeago: 2.0.17
  cached_network_image:
  flutter_svg:
  loading_overlay:


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.

#flutter_icons:
#  image_path_android: "assets/logo.png"
#  image_path_ios: "assets/logo.png"
#  android: true
#  ios: true

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  fonts:
    - family: Signatra
      fonts:
        - asset: assets/fonts/Signatra.ttf
  assets:
    - assets/images/google_signin_button.png
    - assets/images/upload.svg
    - assets/images/search.svg
    - assets/images/activity_feed.svg
    - assets/images/no_content.svg
    - assets/welcome.png
    - assets/report.png
    - assets/no_abuse.png
    - assets/search.png
    - assets/add_post.png
    - assets/new_welcome.png
    - assets/complete_logo.png
    - assets/no_post.png
    - assets/logo.png
    - assets/logo_no_bg.png

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
